/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Diem.pnDiem;
import Diem.pnDiemTheoLop;
import GiangVien.pnGV;
import LopHoc.pnLop;
import MonHoc.pnMonHoc;
import SV_Lop.pn_SV_Lop;
import SinhVien.pnSV;
import TaiKhoan.pnUser;
import ThongKe.pnThongKe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author TranHung
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static String nameLogin;
    private Date today = new Date();
    Locale local = new Locale("vi", "VI");
    DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    String date = d.format(today);

    public Main() {
        initComponents();

        setUser();

        today = new Date();
        today_date.setText(date);
        local = new Locale("en", "EN");
        d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
        date = d.format(today);

        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
                clock.setText(" " + gio + " : " + phut + " : " + giay);
            }
        });
        dongho.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Login_User = new javax.swing.JLabel();
        today_date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        clock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menu_SV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menu_GV = new javax.swing.JButton();
        menu_User = new javax.swing.JButton();
        menu_Lop = new javax.swing.JButton();
        menu_MonHoc = new javax.swing.JButton();
        menu_NhapDiemSV = new javax.swing.JButton();
        menu_SVLop = new javax.swing.JButton();
        menu_XemDiem = new javax.swing.JButton();
        menu_NhapDiemLop = new javax.swing.JButton();
        MainContent = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_HeThong = new javax.swing.JMenu();
        menu_iLogOff = new javax.swing.JMenuItem();
        menu_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MARK SYSTEM MANAGER -  GMARK APTECH");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/banner.png"))); // NOI18N
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/banner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("User:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Today:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-32x32.png"))); // NOI18N

        Login_User.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login_User.setForeground(new java.awt.Color(255, 0, 0));

        today_date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        today_date.setForeground(new java.awt.Color(0, 102, 0));
        today_date.setText("Hour");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(today_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Login_User, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(today_date))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        clock.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Bây giờ là :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_SV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_SV.setForeground(new java.awt.Color(0, 0, 204));
        menu_SV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_SV.setText("Sinh Viên");
        menu_SV.setDefaultCapable(false);
        menu_SV.setHideActionText(true);
        menu_SV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_SV.setIconTextGap(10);
        menu_SV.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_SV.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_SV.setSelected(true);
        menu_SV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SVActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menu_GV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_GV.setForeground(new java.awt.Color(0, 0, 204));
        menu_GV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_GV.setText("Giảng Viên");
        menu_GV.setDefaultCapable(false);
        menu_GV.setHideActionText(true);
        menu_GV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_GV.setIconTextGap(10);
        menu_GV.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_GV.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_GV.setSelected(true);
        menu_GV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_GVActionPerformed(evt);
            }
        });

        menu_User.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_User.setForeground(new java.awt.Color(0, 0, 204));
        menu_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_User.setText("Admin");
        menu_User.setDefaultCapable(false);
        menu_User.setHideActionText(true);
        menu_User.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_User.setIconTextGap(10);
        menu_User.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_User.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_User.setSelected(true);
        menu_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_UserActionPerformed(evt);
            }
        });

        menu_Lop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_Lop.setForeground(new java.awt.Color(0, 0, 204));
        menu_Lop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_Lop.setText("Lớp");
        menu_Lop.setDefaultCapable(false);
        menu_Lop.setHideActionText(true);
        menu_Lop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_Lop.setIconTextGap(10);
        menu_Lop.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_Lop.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_Lop.setSelected(true);
        menu_Lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LopActionPerformed(evt);
            }
        });

        menu_MonHoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_MonHoc.setForeground(new java.awt.Color(0, 0, 204));
        menu_MonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_MonHoc.setText("Môn Học");
        menu_MonHoc.setDefaultCapable(false);
        menu_MonHoc.setHideActionText(true);
        menu_MonHoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_MonHoc.setIconTextGap(10);
        menu_MonHoc.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_MonHoc.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_MonHoc.setSelected(true);
        menu_MonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_MonHocActionPerformed(evt);
            }
        });

        menu_NhapDiemSV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_NhapDiemSV.setForeground(new java.awt.Color(0, 0, 204));
        menu_NhapDiemSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_NhapDiemSV.setText("Nhập Điểm Theo SV");
        menu_NhapDiemSV.setDefaultCapable(false);
        menu_NhapDiemSV.setHideActionText(true);
        menu_NhapDiemSV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_NhapDiemSV.setIconTextGap(10);
        menu_NhapDiemSV.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_NhapDiemSV.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_NhapDiemSV.setSelected(true);
        menu_NhapDiemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_NhapDiemSVActionPerformed(evt);
            }
        });

        menu_SVLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_SVLop.setForeground(new java.awt.Color(0, 0, 204));
        menu_SVLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_SVLop.setText("Sinh Viên - Lớp");
        menu_SVLop.setDefaultCapable(false);
        menu_SVLop.setHideActionText(true);
        menu_SVLop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_SVLop.setIconTextGap(10);
        menu_SVLop.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_SVLop.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_SVLop.setSelected(true);
        menu_SVLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SVLopActionPerformed(evt);
            }
        });

        menu_XemDiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_XemDiem.setForeground(new java.awt.Color(0, 0, 204));
        menu_XemDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_XemDiem.setText("Xem - Thống Kê Điểm");
        menu_XemDiem.setDefaultCapable(false);
        menu_XemDiem.setHideActionText(true);
        menu_XemDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_XemDiem.setIconTextGap(10);
        menu_XemDiem.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_XemDiem.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_XemDiem.setSelected(true);
        menu_XemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_XemDiemActionPerformed(evt);
            }
        });

        menu_NhapDiemLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menu_NhapDiemLop.setForeground(new java.awt.Color(0, 0, 204));
        menu_NhapDiemLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        menu_NhapDiemLop.setText("Nhập Điểm Theo Lớp");
        menu_NhapDiemLop.setDefaultCapable(false);
        menu_NhapDiemLop.setHideActionText(true);
        menu_NhapDiemLop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_NhapDiemLop.setIconTextGap(10);
        menu_NhapDiemLop.setMargin(new java.awt.Insets(1, 14, 2, 14));
        menu_NhapDiemLop.setPreferredSize(new java.awt.Dimension(151, 33));
        menu_NhapDiemLop.setSelected(true);
        menu_NhapDiemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_NhapDiemLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_SV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_GV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_MonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_NhapDiemSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_Lop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_SVLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_XemDiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_NhapDiemLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_NhapDiemLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_NhapDiemSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_XemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_MonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_GV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(menu_SVLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_Lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_SV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainContent.setMinimumSize(new java.awt.Dimension(33, 28));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("HƯỚNG DẪN SỬ DỤNG PHẦN MỀM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(327, 327, 327))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        MainContent.addTab("Main", jPanel6);

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        menu_HeThong.setBackground(new java.awt.Color(204, 204, 255));
        menu_HeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N
        menu_HeThong.setText("System            ");
        menu_HeThong.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N

        menu_iLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_iLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logoff.png"))); // NOI18N
        menu_iLogOff.setText("Log Off");
        menu_iLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_iLogOffActionPerformed(evt);
            }
        });
        menu_HeThong.add(menu_iLogOff);

        menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        menu_Exit.setText(" Exit                     ");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        menu_HeThong.add(menu_Exit);

        jMenuBar2.add(menu_HeThong);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainContent.getAccessibleContext().setAccessibleName("Main");

        setSize(new java.awt.Dimension(1074, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbInputStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInputStudentMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jbInputStudentMouseEntered

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void menu_iLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_iLogOffActionPerformed
        // TODO add your handling code here:
        dispose();
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_menu_iLogOffActionPerformed

    private void menu_SVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SVActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Sinh Viên", new pnSV());
    }//GEN-LAST:event_menu_SVActionPerformed

    private void menu_GVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_GVActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Giảng Viên", new pnGV());
    }//GEN-LAST:event_menu_GVActionPerformed

    private void menu_LopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LopActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Lớp", new pnLop());
    }//GEN-LAST:event_menu_LopActionPerformed

    private void menu_SVLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SVLopActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Thêm lớp cho SV", new pn_SV_Lop());
    }//GEN-LAST:event_menu_SVLopActionPerformed

    private void menu_MonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_MonHocActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Môn Học", new pnMonHoc());
    }//GEN-LAST:event_menu_MonHocActionPerformed

    private void menu_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_UserActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Admin", new pnUser());
    }//GEN-LAST:event_menu_UserActionPerformed

    private void menu_NhapDiemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_NhapDiemSVActionPerformed
        //nhập điểm theo sinh viên
        
        MainContent.removeAll();
        MainContent.add("Vào Diểm theo SV", new pnDiem());
    }//GEN-LAST:event_menu_NhapDiemSVActionPerformed

    private void menu_NhapDiemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_NhapDiemLopActionPerformed
        //Nhập điểm theo lớp và môn 
        
        MainContent.removeAll();
        MainContent.add("Vào Điểm theo Lớp", new pnDiemTheoLop());
    }//GEN-LAST:event_menu_NhapDiemLopActionPerformed

    private void menu_XemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_XemDiemActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        MainContent.add("Thống kê điẻm", new pnThongKe());
    }//GEN-LAST:event_menu_XemDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void setUser() {
        nameLogin = frmLogin.userLogin.getFullname();
        Login_User.setText(nameLogin);

        
    }

    private void jmHelpMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            String command[] = new String[]{"hh.exe", "src\\help.chm"};
            Process child = Runtime.getRuntime().exec(command);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Notice", JOptionPane.OK_OPTION);
        }
    }

    private void jbtinhdiemActionPerformed(java.awt.event.ActionEvent evt) {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_User;
    private javax.swing.JTabbedPane MainContent;
    private javax.swing.JTextField clock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JButton menu_GV;
    private javax.swing.JMenu menu_HeThong;
    private javax.swing.JButton menu_Lop;
    private javax.swing.JButton menu_MonHoc;
    private javax.swing.JButton menu_NhapDiemLop;
    private javax.swing.JButton menu_NhapDiemSV;
    private javax.swing.JButton menu_SV;
    private javax.swing.JButton menu_SVLop;
    private javax.swing.JButton menu_User;
    private javax.swing.JButton menu_XemDiem;
    private javax.swing.JMenuItem menu_iLogOff;
    private javax.swing.JLabel today_date;
    // End of variables declaration//GEN-END:variables
}
