/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ThongKe;

import Diem.Diem;
import Diem.DiemDAO;
import GiangVien.GVDAO;
import GiangVien.GiangVien;
import GiangVien.frmSearch_GV;
import LopHoc.Lop;
import LopHoc.frmSearch_Lop;
import MonHoc.MonHoc;
import MonHoc.frmSearch_MonHoc;
import SinhVien.Sinhvien;
import SinhVien.SinhvienDAO;
import SinhVien.frmSearch_SV;
import chart.Chart;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author TranHung
 */
public class pnThongKe extends javax.swing.JPanel {

    frmSearch_Lop searchLop;
    Lop choosenLop;

    frmSearch_SV searchSV;
    Sinhvien choosenSV;

    frmSearch_GV searchGV;
    GiangVien choosenGV;

    frmSearch_MonHoc searchMH;
    MonHoc choosenMH;

    private DefaultTableModel tbl_data;
    private ArrayList<Diem> dataList;

    int phien;

    /**
     * Creates new form pnThongKe
     */
    public pnThongKe() {
        initComponents();
        rd_lop.doClick();
        loadPhien();

        searchLop = new frmSearch_Lop(this);
        searchMH = new frmSearch_MonHoc(this);
        searchGV = new frmSearch_GV(this);
        searchSV = new frmSearch_SV(this);

        tbl_data = new DefaultTableModel();
        tbl_data.addColumn("STT");
        tbl_data.addColumn("MÃ SV");
        tbl_data.addColumn("Tên SV");
        tbl_data.addColumn("Môn học");
        tbl_data.addColumn("Điểm");
        tbl_data.addColumn("Giảng Viên");
        tbl_data.addColumn("Status");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        text_maMH = new javax.swing.JTextField();
        btn_chonMH = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        btn_chonLop = new javax.swing.JButton();
        rd_sv = new javax.swing.JRadioButton();
        rd_gv = new javax.swing.JRadioButton();
        rd_lop = new javax.swing.JRadioButton();
        btn_clearMH = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Diem = new javax.swing.JTable();
        tab_bieudo = new javax.swing.JTabbedPane();
        rdo_pie = new javax.swing.JRadioButton();
        rdo_bar = new javax.swing.JRadioButton();

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("THỐNG KÊ ĐIỂM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 255));
        label2.setText("Mã Môn Học");

        text_maMH.setEnabled(false);

        btn_chonMH.setText("Chọn");
        btn_chonMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonMHActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label.setForeground(new java.awt.Color(0, 0, 255));
        label.setText("Mã Lớp");

        text.setEnabled(false);

        btn_chonLop.setText("Chọn");
        btn_chonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonLopActionPerformed(evt);
            }
        });

        rd_sv.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(rd_sv);
        rd_sv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_sv.setText("Sinh Viên");
        rd_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_svActionPerformed(evt);
            }
        });

        rd_gv.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(rd_gv);
        rd_gv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_gv.setText("Giảng Viên");
        rd_gv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_gvActionPerformed(evt);
            }
        });

        rd_lop.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(rd_lop);
        rd_lop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_lop.setText("Lớp");
        rd_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_lopActionPerformed(evt);
            }
        });

        btn_clearMH.setText("clear");
        btn_clearMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label)
                    .addComponent(label2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rd_lop)
                        .addGap(14, 14, 14)
                        .addComponent(rd_sv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_gv))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_chonLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(text_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_chonMH, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clearMH)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_sv)
                    .addComponent(rd_gv)
                    .addComponent(rd_lop))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chonLop)
                    .addComponent(label))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chonMH)
                    .addComponent(label2)
                    .addComponent(btn_clearMH))
                .addGap(25, 25, 25))
        );

        tab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_Diem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Diem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(tbl_Diem);

        tab.addTab("---", jScrollPane3);

        tab_bieudo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rdo_pie);
        rdo_pie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdo_pie.setForeground(new java.awt.Color(51, 51, 255));
        rdo_pie.setText("Biểu đồ tròn");
        rdo_pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_pieActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_bar);
        rdo_bar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdo_bar.setForeground(new java.awt.Color(51, 51, 255));
        rdo_bar.setText("Biểu đồ cột");
        rdo_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_barActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tab_bieudo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rdo_bar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_pie)
                                .addGap(60, 60, 60)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_bar)
                            .addComponent(rdo_pie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tab_bieudo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chonMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonMHActionPerformed
        // TODO add your handling code here:

        searchMH.setLocation(400, 200);
        searchMH.setVisible(true);
    }//GEN-LAST:event_btn_chonMHActionPerformed

    private void btn_chonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonLopActionPerformed
        // TODO add your handling code here:
        if (phien == 1) {
            searchLop.setVisible(true);
            searchLop.setLocation(400, 200);

        } else if (phien == 2) {
            searchSV.setVisible(true);
            searchSV.setLocation(400, 200);

        } else if (phien == 3) {
            searchGV.setVisible(true);
            searchGV.setLocation(400, 200);

        }
    }//GEN-LAST:event_btn_chonLopActionPerformed

    private void rdo_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_barActionPerformed
        // TODO add your handling code here:
        thongKe();
    }//GEN-LAST:event_rdo_barActionPerformed

    private void rdo_pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_pieActionPerformed
        // TODO add your handling code here:
        thongKe();
    }//GEN-LAST:event_rdo_pieActionPerformed

    private void rd_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_svActionPerformed
        // TODO add your handling code here:
        loadPhien();
        loadDdataa();
    }//GEN-LAST:event_rd_svActionPerformed

    private void rd_gvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_gvActionPerformed
        // TODO add your handling code here:
        loadPhien();
        loadDdataa();
    }//GEN-LAST:event_rd_gvActionPerformed

    private void rd_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_lopActionPerformed
        // TODO add your handling code here:
        loadPhien();
        if (choosenLop != null) {
            loadDdataa();
        }
    }//GEN-LAST:event_rd_lopActionPerformed

    private void btn_clearMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearMHActionPerformed
        // TODO add your handling code here:
        choosenMH = null;
        text_maMH.setText("");
        loadDdataa();
    }//GEN-LAST:event_btn_clearMHActionPerformed

    private void loadDdataa() {
        //xoa dât cu
        while (tbl_data.getRowCount() > 0) {
            tbl_data.removeRow(0);
        }
        dataList = new ArrayList<>();
        dataList.clear();
        if (phien == 1) {
            try {
                tab.setTitleAt(0, "Danh sách điểm môn " + choosenMH.getMaMH() + " - Lớp " + choosenLop.getMaLop());
                dataList = new DiemDAO().getByLop_MonHoc(choosenLop.getMaLop(), choosenMH.getMaMH());
            } catch (Exception e) {
                System.out.println("Không lấy được data");
            }

        } else if (phien == 2) {
            try {
                tab.setTitleAt(0, "Danh sách điểm cuả Sinh Viên " + choosenSV.getTenSV());
                if (choosenMH==null) {
                    dataList = new DiemDAO().getByMaSV(choosenSV.getMaSV(),null);
                }else{
                    dataList = new DiemDAO().getByMaSV(choosenSV.getMaSV(),choosenMH.getMaMH());
                }
            } catch (Exception e) {
                System.out.println("Không lấy được data");
            }

        } else if (phien == 3) {

            try {
                tab.setTitleAt(0, "Danh sách điểm của Giảng viên " + choosenGV.getTenGV());
                if (choosenMH == null) {
                    dataList = new DiemDAO().getByMaGV(choosenGV.getId(), null);
                } else {
                    dataList = new DiemDAO().getByMaGV(choosenGV.getId(), choosenMH.getMaMH());
                }

            } catch (Exception e) {
                System.out.println("Không lấy được data");
            }
        }

        for (Diem diem : dataList) {
            String status = "DIST";
            if (diem.getDiem() < 4) {
                status = "FAIL";
            } else if (diem.getDiem() < 6.5) {
                status = "PASS";
            } else if (diem.getDiem() < 8.0) {
                status = "CREDIT";
            }

            tbl_data.addRow(new Object[]{
                tbl_data.getRowCount() + 1,
                diem.getMaSV(),
                new SinhvienDAO().getByID(diem.getMaSV()).get(0).getTenSV(),
                diem.getMamh(),
                diem.getDiem(),
                new GVDAO().getByID(diem.getMaGV()).get(0).getTenGV(),
                status
            });
        }
        tbl_Diem.setModel(tbl_data);

        rdo_bar.doClick();
        thongKe();
    }

    private void thongKe() {
        tab_bieudo.removeAll();
        ChartPanel pnChart;

//        pnChart = Chart.getBarChartPanel(dataList);
        if (rdo_bar.isSelected()) {
            pnChart = Chart.getBarChartPanel(dataList);
        } else {
            pnChart = Chart.getPieChartPanel(dataList);
        }

        tab_bieudo.add(pnChart);

    }

    public void receiveLop(Lop lop) {
        choosenLop = lop;
        text.setText(choosenLop.getMaLop());
        searchLop.setVisible(false);

        if (choosenMH != null) {
            loadDdataa();
        }
    }

    public void receiveMH(MonHoc mh) {
        choosenMH = mh;
        text_maMH.setText(mh.getMaMH());
        searchMH.setVisible(false);

        //hien thi diem cua nhung nguoi da co diem ra table
        loadDdataa();
    }

    public void receiveGV(GiangVien gv) {
        choosenGV = gv;
        text.setText(choosenGV.getTenGV());
        searchGV.setVisible(false);
        loadDdataa();
    }

    public void receiveSV(Sinhvien sv) {
        choosenSV = sv;
        text.setText(choosenSV.getMaSV() + "-" + choosenSV.getTenSV());
        searchSV.setVisible(false);
        loadDdataa();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chonLop;
    private javax.swing.JButton btn_chonMH;
    private javax.swing.JButton btn_clearMH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JRadioButton rd_gv;
    private javax.swing.JRadioButton rd_lop;
    private javax.swing.JRadioButton rd_sv;
    private javax.swing.JRadioButton rdo_bar;
    private javax.swing.JRadioButton rdo_pie;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTabbedPane tab_bieudo;
    private javax.swing.JTable tbl_Diem;
    private javax.swing.JTextField text;
    private javax.swing.JTextField text_maMH;
    // End of variables declaration//GEN-END:variables

    private void loadPhien() {
        if (choosenMH != null) {
            text_maMH.setText(choosenMH.getMaMH());
        } else {
            text_maMH.setText("");
        }

        if (rd_lop.isSelected()) {
            phien = 1;
            label.setText("Lớp");

            if (choosenLop == null) {
                text.setText("");
            } else {
                text.setText(choosenLop.getMaLop());
            }

        } else if (rd_sv.isSelected()) {
            phien = 2;
            label.setText("Sinh Viên");

            if (choosenSV == null) {
                text.setText("");
            } else {
                text.setText(choosenSV.getMaSV() + "-" + choosenSV.getTenSV());
            }

        } else if (rd_gv.isSelected()) {
            phien = 3;
            label.setText("Giảng Viên");

            if (choosenGV == null) {
                text.setText("");
            } else {
                text.setText(choosenGV.getTenGV());
            }
        }
    }

}
