/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Diem;

import GiangVien.GVDAO;
import GiangVien.GiangVien;
import GiangVien.frmSearch_GV;
import LopHoc.Lop;
import LopHoc.frmSearch_Lop;
import MonHoc.MonHoc;
import MonHoc.MonHocDAO;
import MonHoc.frmSearch_MonHoc;
import SinhVien.Sinhvien;
import SinhVien.SinhvienDAO;
import SinhVien.frmSearch_SV;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Validate;

/**
 *
 * @author TranHung
 */
public class pnDiemTheoLop extends javax.swing.JPanel {

    frmSearch_Lop  searchLop;
    Lop choosenLop ;
    
    frmSearch_SV searchSV;
    Sinhvien choosenSV;
    
    frmSearch_GV searchGV;
    GiangVien choosenGV;
    
    frmSearch_MonHoc searchMH;
    MonHoc choosenMH;
    
    private DefaultTableModel tbl_data;
    private ArrayList<Diem> dataList;
    private int i;
    /**
     * Creates new form pnDiemTheoLop
     */
    public pnDiemTheoLop() {
        initComponents();
        searchLop = new frmSearch_Lop(this);
        searchLop.setLocation(400, 200);
        
        searchMH = new frmSearch_MonHoc(this);
        
        searchGV = new frmSearch_GV(this);
        
        tbl_data = new DefaultTableModel();
        tbl_data.addColumn("STT");
        tbl_data.addColumn("MÃ SV");
        tbl_data.addColumn("Tên SV");
        tbl_data.addColumn("Môn học");
        tbl_data.addColumn("Điểm");
        tbl_data.addColumn("Giảng Viên");
        tbl_data.addColumn("Ngày tạo");
        tbl_data.addColumn("Ngày sửa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        text_diem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_GV = new javax.swing.JTextField();
        text_maSV = new javax.swing.JTextField();
        text_maMH = new javax.swing.JTextField();
        btn_chonMH = new javax.swing.JButton();
        btn_chonGV = new javax.swing.JButton();
        btn_chonSV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        text_maLop = new javax.swing.JTextField();
        btn_chonLop = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Diem = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARK INFORMATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        text_diem.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Mã Sinh Viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Mã Môn Học");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Điểm");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Giảng Viên");

        text_GV.setEnabled(false);

        text_maSV.setEnabled(false);

        text_maMH.setEnabled(false);

        btn_chonMH.setText("Chọn");
        btn_chonMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonMHActionPerformed(evt);
            }
        });

        btn_chonGV.setText("Chọn");
        btn_chonGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonGVActionPerformed(evt);
            }
        });

        btn_chonSV.setText("Chọn");
        btn_chonSV.setEnabled(false);
        btn_chonSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonSVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mã Lớp");

        text_maLop.setEnabled(false);

        btn_chonLop.setText("Chọn");
        btn_chonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(text_maLop, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_chonLop))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(text_maMH, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(text_GV)
                                .addComponent(text_maSV))
                            .addComponent(text_diem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_chonSV, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_chonGV, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btn_chonMH, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_maLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chonLop)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chonMH)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(btn_chonGV))
                    .addComponent(text_GV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_chonSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 0, 0));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setEnabled(false);
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 0, 0));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_delete.setIconTextGap(2);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 0, 0));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.setEnabled(false);
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reset)
                .addGap(52, 52, 52))
        );

        tbl_Diem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Diem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_Diem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DiemMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_DiemMouseReleased(evt);
            }
        });
        tbl_Diem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_DiemKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Diem);

        tab.addTab("---", jScrollPane3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chonMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonMHActionPerformed
        // TODO add your handling code here:

        searchMH.setLocation(400, 200);
        searchMH.setVisible(true);
    }//GEN-LAST:event_btn_chonMHActionPerformed

    private void btn_chonGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonGVActionPerformed
        // TODO add your handling code here:
        searchGV.setVisible(true);
        searchGV.setLocation(400, 200);
    }//GEN-LAST:event_btn_chonGVActionPerformed

    private void btn_chonSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonSVActionPerformed
        // TODO add your handling code here:
        searchSV = new frmSearch_SV(this);
        searchSV.setVisible(true);
        searchSV.setLocation(400, 200);
    }//GEN-LAST:event_btn_chonSVActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        if (!checkInfo()) {
            return;
        }

        Diem diem = new Diem(
            Float.parseFloat(text_diem.getText()),
            choosenSV.getMaSV(),
            choosenMH.getMaMH(),
            choosenGV.getId(),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss"),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss")
        );

        new DiemDAO().updateByID(dataList.get(i).getMaDiem(),diem);

        loadDdataa();
        btn_chonMH.setEnabled(true);
        btn_add.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);

        text_GV.setText("");
        text_diem.setText("");
        btn_reset.doClick();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int maDiem = dataList.get(i).getMaDiem();
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa điểm này ?");

        //        System.out.println(chon); -> yes = 0 ; no = 1 , cancell = 2
        if (chon == 0) {
            new DiemDAO().deleteDiem(maDiem);
            loadDdataa();
            btn_reset.doClick();
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        if (!checkInfo()) {
            return;
        }

        Diem diem = new Diem(
            Float.parseFloat(text_diem.getText()),
            choosenSV.getMaSV(),
            choosenMH.getMaMH(),
            choosenGV.getId(),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss"),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss")
        );

        new DiemDAO().addNew(diem);

        loadDdataa();
        btnStatus(0);
        text_maSV.setText("");
        text_diem.setText("");
        text_diem.setEnabled(false);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed

        btn_add.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_chonMH.setEnabled(false);

        choosenSV=null;
        text_maSV.setText("");
        text_diem.setText("");
        
        loadDdataa();
        btn_chonMH.setEnabled(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_chonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonLopActionPerformed
        // TODO add your handling code here:
        searchLop.setVisible(true);
    }//GEN-LAST:event_btn_chonLopActionPerformed

    private void tbl_DiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_DiemKeyReleased

    }//GEN-LAST:event_tbl_DiemKeyReleased

    private void tbl_DiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DiemMouseReleased

    }//GEN-LAST:event_tbl_DiemMouseReleased

    private void tbl_DiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DiemMouseClicked
        // TODO add your handling code here:
        btn_chonMH.setEnabled(false);
        i = tbl_Diem.getSelectedRow();

        Diem diem = dataList.get(i);
        choosenMH = new MonHocDAO().searchID(diem.getMamh()).get(0);
        text_maMH.setText(choosenMH.getMaMH());

        choosenGV = new GVDAO().getByID( diem.getMaGV()).get(0);
        text_GV.setText(choosenGV.getTenGV());
        
        //lấy ra choosen SV từ bảng:
        String maSV = diem.getMaSV();
        choosenSV = new SinhvienDAO().getByID(maSV).get(0);
        text_maSV.setText(choosenSV.getTenSV());

        text_diem.setText(Float.toString(diem.getDiem()));

        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        
        text_diem.setEnabled(true);
    }//GEN-LAST:event_tbl_DiemMouseClicked

    public void receiveLop(Lop lop){
        choosenLop = lop;
        text_maLop.setText(choosenLop.getMaLop());
        searchLop.setVisible(false);
        
        if (choosenMH!=null) {
            loadDdataa();
        }
    }
    public void receiveMH(MonHoc mh){
        choosenMH = mh;
        text_maMH.setText(mh.getMaMH());
        searchMH.setVisible(false);
        
        btn_chonGV.setEnabled(true);
        btn_chonSV.setEnabled(true);
        
        //hien thi diem cua nhung nguoi da co diem ra table
        loadDdataa();
    }
    public void receiveGV(GiangVien gv){
        choosenGV = gv;
        text_GV.setText(gv.getTenGV());
        searchGV.setVisible(false);
        
        //mở nút chọn sv
        btn_chonSV.setEnabled(true);
    }
    public void receiveSV(Sinhvien sv){
        choosenSV = sv;
        text_maSV.setText(choosenSV.getMaSV()+" - "+choosenSV.getTenSV());
        searchSV.setVisible(false);
        text_diem.setEnabled(true);
        
        btnStatus(1);
    }

    public Lop getChoosenLop() {
        return choosenLop;
    }

    public MonHoc getChoosenMH() {
        return choosenMH;
    }
    
    
    
    public void btnStatus(int i){
        if (i==0) {
            btn_add.setEnabled(false);
            btn_delete.setEnabled(false);
            btn_update.setEnabled(false);
        }else if (i==1) {
            btn_add.setEnabled(true);
            btn_delete.setEnabled(false);
            btn_update.setEnabled(false);
        }else if (i==2) {
            btn_add.setEnabled(false);
            btn_delete.setEnabled(true);
            btn_update.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_chonGV;
    private javax.swing.JButton btn_chonLop;
    private javax.swing.JButton btn_chonMH;
    private javax.swing.JButton btn_chonSV;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbl_Diem;
    private javax.swing.JTextField text_GV;
    private javax.swing.JTextField text_diem;
    private javax.swing.JTextField text_maLop;
    private javax.swing.JTextField text_maMH;
    private javax.swing.JTextField text_maSV;
    // End of variables declaration//GEN-END:variables

    private boolean checkInfo() {
        Validate v = new Validate();
        
        if (choosenGV==null) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giảng viên", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            btn_chonGV.requestFocus();
            return false;
        }
        else if (!v.checkDiem(text_diem.getText())) {
            JOptionPane.showMessageDialog(this, "Điểm không hợp lệ", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_diem.requestFocus();
            return false;
        }
        return true;
    }

    private void loadDdataa() {
        tab.setTitleAt(0, "Danh sách điểm môn "+choosenMH.getMaMH()+" - Lớp "+choosenLop.getMaLop());
        //xoa dât cu
        while(tbl_data.getRowCount()>0){
            tbl_data.removeRow(0);
        }
       
        dataList = new DiemDAO().getByLop_MonHoc(choosenLop.getMaLop(), choosenMH.getMaMH());
        
        for (Diem diem : dataList) {
            
            tbl_data.addRow(new Object[]{
                tbl_data.getRowCount() + 1,
                diem.getMaSV(),
                new SinhVien.SinhvienDAO().getByID(diem.getMaSV()).get(0).getTenSV(),
                diem.getMamh(),
                diem.getDiem(),
                new GVDAO().getByID(diem.getMaGV()).get(0).getTenGV() ,
                diem.getCreated_at(),
                diem.getUpdated_at()
            });
        }
        tbl_Diem.setModel(tbl_data);
    }
}
