/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SinhVien;

import Diem.DiemDAO;
import SV_Lop.SV_LopDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import utils.Validate;

/**
 *
 * @author TranHung
 */
public class pnSV extends javax.swing.JPanel {

    private List<Sinhvien> listSV;
    private int row;
    DefaultTableModel tbl_data;
    int total_page;
    final int limit = 5;
    int index;

    /**
     * Creates new form pnSV
     */
    public pnSV() {
        initComponents();
        
        index = 1;
        
        tbl_data = new DefaultTableModel();
        tbl_data.addColumn("STT");
        tbl_data.addColumn("Ma SV");
        tbl_data.addColumn("Ten SV");
        tbl_data.addColumn("He dao tao");
        tbl_data.addColumn("SDT");
        tbl_data.addColumn("Email");
        tbl_data.addColumn("Dia Chi");
        tbl_data.addColumn("Gioi tinh");
        tbl_data.addColumn("Ngay Sinh");
        tbl_data.addColumn("Ngay tao");
        tbl_data.addColumn("Ngay update");
        
        tbl_SinhVien.setModel(tbl_data);
        
        loadData();
        load_CbbHedaotao();
        load_CbbGiotinh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SinhVien = new javax.swing.JTable();
        pn_search_page = new javax.swing.JPanel();
        text_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pn_page = new javax.swing.JPanel();
        btn_model1 = new javax.swing.JButton();
        btn_model = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        text_maSV = new javax.swing.JTextField();
        text_tenSV = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        text_sdt = new javax.swing.JTextField();
        text_diachi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        cbb_hedaotao = new javax.swing.JComboBox();
        calendar_ngaysinh = new com.toedter.calendar.JDateChooser();
        cbb_gioitinh = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STUDENT INFORMATION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbl_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Số Điện Thoại", "Email", "Hệ Đào Tạo", "Ngay tao", "Ngay cap nhat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SinhVienMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_SinhVienMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_SinhVien);

        pn_search_page.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchKeyReleased(evt);
            }
        });

        jLabel4.setText("Tên/Mã SV");

        btn_model1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_model1.setText("1");
        btn_model1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_model1.setMaximumSize(new java.awt.Dimension(25, 25));
        btn_model1.setPreferredSize(new java.awt.Dimension(25, 25));
        pn_page.add(btn_model1);

        btn_model.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_model.setText("2");
        btn_model.setAlignmentY(0.0F);
        btn_model.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_model.setMaximumSize(new java.awt.Dimension(25, 25));
        btn_model.setPreferredSize(new java.awt.Dimension(25, 25));
        pn_page.add(btn_model);

        javax.swing.GroupLayout pn_search_pageLayout = new javax.swing.GroupLayout(pn_search_page);
        pn_search_page.setLayout(pn_search_pageLayout);
        pn_search_pageLayout.setHorizontalGroup(
            pn_search_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_search_pageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(text_search, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(149, 149, 149)
                .addComponent(pn_page, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_search_pageLayout.setVerticalGroup(
            pn_search_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_search_pageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_search_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_search_pageLayout.createSequentialGroup()
                .addComponent(pn_page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel8.setForeground(new java.awt.Color(153, 153, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Mã Sinh Viên");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("Họ Tên");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setText("Hệ Đào Tạo");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Số Điện Thoại");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 204));
        jLabel23.setText("Giới Tính");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("Địa Chỉ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setText("Ngày Sinh");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("Email");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_tenSV)
                    .addComponent(text_maSV)
                    .addComponent(text_sdt)
                    .addComponent(cbb_hedaotao, 0, 163, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendar_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(text_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_tenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(calendar_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(text_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_hedaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(text_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 0, 0));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setEnabled(false);
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 0, 0));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_delete.setIconTextGap(2);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 0, 0));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        btn_add.setText("AddNew");
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_search_page, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_search_page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_SinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SinhVienMouseClicked
        controll_btn(false);

        int i = tbl_SinhVien.getSelectedRow();
        row = Integer.parseInt(tbl_SinhVien.getValueAt(i, 0).toString())-1;
        //        String strdate = tbl_SinhVien.getValueAt(row, 2).toString();
        //        Date date = utils.DateTime.String2Date(strdate);

        Sinhvien sv = listSV.get(row);

        //check xem da co rang buoc FK chưa : tìm trên bảng sv_lop xem có sinh vien này chưa
        if (new SV_LopDAO().checkSV(sv.getMaSV()) || new Diem.DiemDAO().checkExistMaSV(sv.getMaSV())) {
            text_maSV.setEnabled(false);
        } else {
            text_maSV.setEnabled(true);
        }

        text_maSV.setText(sv.getMaSV());
        text_tenSV.setText(sv.getTenSV());
        text_email.setText(sv.getEmail());
        text_diachi.setText(sv.getDiachi());
        text_sdt.setText(sv.getSdt());
        calendar_ngaysinh.setDate(utils.DateTime.String2Date(sv.getNgaysinh()));
        cbb_gioitinh.setSelectedItem(sv.getGioitinh());
        cbb_hedaotao.setSelectedItem(sv.getHedaotao());
    }//GEN-LAST:event_tbl_SinhVienMouseClicked

    private void tbl_SinhVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SinhVienMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_SinhVienMouseReleased

    private void text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchKeyReleased
        // TODO add your handling code here:
        index = 1;
        loadData();
    }//GEN-LAST:event_text_searchKeyReleased

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (!checkInfo()) {
            return;
        }

        //maGV can sua
        String maSV = listSV.get(row).getMaSV();

        Sinhvien sv = new Sinhvien(
                utils.Uppercase.UpperID(text_maSV.getText()),
                utils.Uppercase.UpperName(text_tenSV.getText()),
                utils.Uppercase.UpperName(text_diachi.getText()),
                text_email.getText(),
                cbb_gioitinh.getSelectedItem().toString(),
                text_sdt.getText(),
                utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd hh:mm:ss"),
                cbb_hedaotao.getSelectedItem().toString(),
                utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss"),
                utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss")
        );

        //update lại ở các bảng liên quan : bảng điểm
        //alter table diem set maSV = mã mới where maSV = mã cũ
        new SinhvienDAO().updateByID(maSV, sv);

        btn_reset.doClick();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        //ma muon xoa:
        String maSV = listSV.get(row).getMaSV();
        
        //confirm trước khi xóa : yes = 0 ; no = 1 , cancell = 2
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tất cả dữ liệu liên quan đến sinh viên này ?" + listSV.get(row).getTenSV() + " ?");
        if (chon == 0) {
            //xóa trên table diem
            new DiemDAO().deleteByMaSV(maSV);
            
            //xoa tren bảng sv_lop
            new SV_LopDAO().DeleteByMaSV(maSV);
            
            //xoa trên bảng sinhvien
            new SinhvienDAO().deleteSV(maSV);
            btn_reset.doClick();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (!checkInfo()) {
            return;
        }
        
        if (new SinhvienDAO().checkExists(text_maSV.getText())) {
            JOptionPane.showMessageDialog(this, "Mã SV đã được sử dụng", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_maSV.requestFocus();
            return ;
        }
        
        Sinhvien sv = new Sinhvien(
                utils.Uppercase.UpperID(text_maSV.getText()),
                utils.Uppercase.UpperName(text_tenSV.getText()),
                utils.Uppercase.UpperName(text_diachi.getText()),
                text_email.getText(),
                cbb_gioitinh.getSelectedItem().toString(),
                text_sdt.getText(),
                utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd hh:mm:ss"),
                cbb_hedaotao.getSelectedItem().toString(),
                utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss"),
                utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss")
        );

        new SinhvienDAO().addNew(sv);
        btn_reset.doClick();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed

        controll_btn(true);
        text_maSV.setEnabled(true);
        text_maSV.setText("");
        text_tenSV.setText("");
        text_email.setText("");
        text_diachi.setText("");
        text_sdt.setText("");
        calendar_ngaysinh.setDate(null);
        cbb_gioitinh.setSelectedIndex(0);
        cbb_hedaotao.setSelectedIndex(0);

        loadData();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void load_CbbHedaotao() {
        DefaultComboBoxModel hedaotao = new DefaultComboBoxModel();
        hedaotao.addElement("--Chọn Hệ Đào Tạo--");
        hedaotao.addElement("ADSE");
        hedaotao.addElement("DISM");

        cbb_hedaotao.setModel(hedaotao);
    }

    private void load_CbbGiotinh() {
        DefaultComboBoxModel giotinh = new DefaultComboBoxModel();
        giotinh.addElement("--Chọn Giới Tính--");
        giotinh.addElement("Nam");
        giotinh.addElement("Nữ");

        cbb_gioitinh.setModel(giotinh);
    }

    private void controll_btn(boolean status) {
        if (status) {
            btn_add.setEnabled(true);
            btn_delete.setEnabled(false);
            btn_update.setEnabled(false);
        } else {
            btn_add.setEnabled(false);
            btn_delete.setEnabled(true);
            btn_update.setEnabled(true);
        }
    }

    private void loadData() {
        //truoc tien can xoa du lieu cu (nhung dong co rowcount > 0)
        while (tbl_data.getRowCount() > 0) {
            tbl_data.removeRow(0);
        }
        
        String s = text_search.getText();
        listSV = new SinhvienDAO().search(s);
        
        //load phan trang
        double p = (double) listSV.size()/limit;
        total_page = (int) Math.ceil(p) ;
        int start = limit*(index-1);
        
        showRow();

        for (int i = start; i < start+limit; i++) {
            if(i<listSV.size()){
                tbl_data.addRow(new Object[]{
                    i+1,
                    listSV.get(i).getMaSV(),
                    listSV.get(i).getTenSV(),
                    listSV.get(i).getHedaotao(),
                    listSV.get(i).getSdt(),
                    listSV.get(i).getEmail(),
                    listSV.get(i).getDiachi(),
                    listSV.get(i).getGioitinh(),
                    listSV.get(i).getNgaysinh(),
                    listSV.get(i).getCreated_at(),
                    listSV.get(i).getUpdated_at()
                });
            }
        }
        
        tbl_SinhVien.setModel(tbl_data);
    }
    
    private void showRow() {
        pn_page.removeAll();
        pn_page.revalidate();
        pn_page.repaint();

        JButton pre = new JButton();
        pre.setFont(btn_model.getFont());
        pre.setText("<<");
        pn_page.add(pre);

        for (int i = 1; i <= total_page; i++) {
            if (i + 1 < index && i != 1) {
                continue;
            }

            if (i - 1 > index && i != total_page) {
                continue;
            }

            JButton btn = getButton(i);
            pn_page.add(btn);
        }

        JButton next = new JButton();
        next.setFont(btn_model.getFont());
        next.setText(">>");
        pn_page.add(next);

        if (index == 1) {
            pre.setEnabled(false);
        }
        if (index == total_page) {
            next.setEnabled(false);
        }
       
        pre.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                index--;
                loadData();
            }
        });
         
        next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                 index++;
                 loadData();
            }
        });

    }
    
    private JButton getButton(int i) {
        JButton btn = new JButton();
        btn.setFont(btn_model.getFont());
        
        btn.setText("" + i);

        btn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                index = Integer.parseInt(btn.getText());
                loadData();
            }
        });

        if (index == i) {
            btn.setBackground(Color.GRAY);
            btn.setFont(btn_model1.getFont());
        }
        return btn;
    }
    
    private boolean checkInfo() {
        Validate v = new Validate();

        //neu check ma sv khong hop le : chỉ có số và chữ
        if (!v.checkID(text_maSV.getText())) {
            JOptionPane.showMessageDialog(this, "Mã SV chỉ gồm các kí tự a->z 0->9 và có ít nhất 2 kí tự", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_maSV.requestFocus();
            return false;

        //neu ten sv khong hop le  :phải có dấu cách
        } else if (!v.checkExistSpace(text_tenSV.getText()) ) {
            JOptionPane.showMessageDialog(this, "Tên phải có ít nhất 2 chữ", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_tenSV.requestFocus();
            return false;

        //neu sdt khong hop le 8-13 chữ số
        } else if (!v.checkPhone(text_sdt.getText())) {
            JOptionPane.showMessageDialog(this, "Lỗi Số Điện Thoại", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_sdt.requestFocus();
            return false;
        }
        
        //dia chi phai co dau cách
        else if (!v.checkExistSpace(text_diachi.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập dia chi sinh vien sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_diachi.requestFocus();
            return false;

        //email phải có @ , phần . có 2-4 kí tự
        }else if (!v.checkEmail(text_email.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập Email không hợp lệ", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_email.requestFocus();
            return false;

        }
        
        else if (cbb_gioitinh.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            cbb_gioitinh.requestFocus();
            return false;
        }
        
        else if (cbb_hedaotao.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hệ đào tạo", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            cbb_hedaotao.requestFocus();
            return false;
        }
        
        else if (calendar_ngaysinh.getDate()==null) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập ngày sinh", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            calendar_ngaysinh.requestFocus();
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_model;
    private javax.swing.JButton btn_model1;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private com.toedter.calendar.JDateChooser calendar_ngaysinh;
    private javax.swing.JComboBox cbb_gioitinh;
    private javax.swing.JComboBox cbb_hedaotao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_page;
    private javax.swing.JPanel pn_search_page;
    private javax.swing.JTable tbl_SinhVien;
    private javax.swing.JTextField text_diachi;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_maSV;
    private javax.swing.JTextField text_sdt;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_tenSV;
    // End of variables declaration//GEN-END:variables
}
