/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiangVien;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import utils.Validate;

/**
 *
 * @author TranHung
 */
public class pnGV extends javax.swing.JPanel {
    
    private DefaultTableModel tbl_data;
    private ArrayList<GiangVien> data;
    private int i;

    /**
     * Creates new form pnGV
     */
    public pnGV() {
        initComponents();
         tbl_data = new DefaultTableModel();

        tbl_data.addColumn("STT");
        tbl_data.addColumn("Ma GV");
        tbl_data.addColumn("Ten GV");
        tbl_data.addColumn("Gioi tinh");
        tbl_data.addColumn("SDT");
        tbl_data.addColumn("Email");
        tbl_data.addColumn("Dia Chi");
        tbl_data.addColumn("Ngay sinh");
        loadData();
        loadCbb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_gv = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        text_tenGV = new javax.swing.JTextField();
        text_diachi = new javax.swing.JTextField();
        text_sdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbb_gioitinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        calendar_ngaysinh = new com.toedter.calendar.JDateChooser();

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TEACHER INFORMATION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 0, 0));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setEnabled(false);
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 0, 0));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_delete.setIconTextGap(2);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 0, 0));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        btn_add.setText("AddNew");
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reset)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        tbl_gv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ Tên", "Email", "Địa Chỉ", "Số Điện Thoại", "Ngày tạo", "Ngày update"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_gv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_gv);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Giới tính");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Địa Chỉ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Họ Tên");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Điện Thoại");

        cbb_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Ngày sinh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(text_tenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text_sdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_diachi, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(calendar_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbb_gioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(text_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(calendar_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(!checkInfo()){
            return;
        }

        //maGV can sua
        int maGV = data.get(i).getId();

        String date = utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd");
        GiangVien gv = new GiangVien(
            utils.Uppercase.UpperName(text_tenGV.getText()),
            utils.Uppercase.UpperName(text_diachi.getText()),
            text_sdt.getText(),
            text_email.getText(),
            cbb_gioitinh.getSelectedItem().toString() ,
            utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd"),
            data.get(i).getCreated_at(),
            data.get(i).getUpdated_at()
        );

        new GVDAO().updateByID(maGV, gv);

        btn_reset.doClick();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        //maGV ,uon xoa:
        int maGV = data.get(i).getId();

        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa Giảng Viên "+data.get(i).getTenGV()+" ?");

        //        System.out.println(chon); -> yes = 0 ; no = 1 , cancell = 2
        if (chon == 0) {
            new GVDAO().deleteGiangVien(maGV);
            btn_reset.doClick();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(!checkInfo()){
            return;
        }
        
        String date = utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd");
        GiangVien gv = new GiangVien(
            utils.Uppercase.UpperName(text_tenGV.getText()),
            utils.Uppercase.UpperName(text_diachi.getText()),
            text_sdt.getText(),
            text_email.getText(),
            cbb_gioitinh.getSelectedItem().toString() ,
            utils.DateTime.Date2String(calendar_ngaysinh.getDate(), "yyyy-MM-dd"),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss"),
            utils.DateTime.getTimeNow("yyyy-MM-dd HH:mm:ss")
        );

        new GVDAO().addNew(gv);
        btn_reset.doClick();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed

        controll_btn(true);
        text_tenGV.setText("");
        text_diachi.setText("");
        text_email.setText("");
        text_sdt.setText("");
        cbb_gioitinh.setSelectedIndex(0);
        calendar_ngaysinh.setDate(null);

        loadData();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_gvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gvMouseClicked
        controll_btn(false);
        btn_delete.setEnabled(false);
        
        //lay ra index
        i = tbl_gv.getSelectedRow();

        //lấy lại obj:
        GiangVien gv = data.get(i);

        //fill lại dữ liệu:
        text_tenGV.setText(gv.getTenGV());
        text_diachi.setText(gv.getDiachi());
        text_email.setText(gv.getEmail());
        text_sdt.setText(gv.getSdt());
        cbb_gioitinh.setSelectedItem(gv.getGioitinh());
        calendar_ngaysinh.setDate(utils.DateTime.String2Date(gv.getNgaysinh()));

    }//GEN-LAST:event_tbl_gvMouseClicked

    
    private void loadData() {
        //truoc tien can xoa du lieu cu (nhung dong co rowcount > 0)
        while (tbl_data.getRowCount() > 0) {
            tbl_data.removeRow(0);
        }

        data = new GVDAO().search("");
        for (GiangVien gv : data) {
            tbl_data.addRow(new Object[]{
                tbl_data.getRowCount() + 1,
                gv.getId(),
                gv.getTenGV(),
                gv.getGioitinh(),
                gv.getSdt(),
                gv.getEmail(),
                gv.getDiachi(),
                gv.getNgaysinh()
            });
        }

        tbl_gv.setModel(tbl_data);
    }

    private void controll_btn(boolean status) {
        if (status) {
            btn_add.setEnabled(true);
            btn_delete.setEnabled(false);
            btn_update.setEnabled(false);
        } else {
            btn_add.setEnabled(false);
            btn_delete.setEnabled(true);
            btn_update.setEnabled(true);
        }
    }
    
    private boolean checkInfo(){
        Validate v = new Validate();

        if (!v.checkExistSpace(text_tenGV.getText()) ) {
            JOptionPane.showMessageDialog(this, "Tên phải có ít nhất 2 chữ", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_tenGV.requestFocus();
            return false;

        //neu sdt khong hop le 8-13 chữ số
        } else if (!v.checkPhone(text_sdt.getText())) {
            JOptionPane.showMessageDialog(this, "Lỗi Số Điện Thoại", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_sdt.requestFocus();
            return false;
        }
        
        //dia chi phai co dau cách
        else if (!v.checkExistSpace(text_diachi.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập dia chi sinh vien sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_diachi.requestFocus();
            return false;

        //email phải có @ , phần . có 2-4 kí tự
        }else if (!v.checkEmail(text_email.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập Email không hợp lệ", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            text_email.requestFocus();
            return false;

        }
        
        else if (cbb_gioitinh.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            cbb_gioitinh.requestFocus();
            return false;
        }
        
        else if (calendar_ngaysinh.getDate()==null) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập ngày sinh", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            calendar_ngaysinh.requestFocus();
            return false;
        }
        return true;
    }
    
    private void loadCbb(){
        DefaultComboBoxModel cbb = new DefaultComboBoxModel<>();
        cbb.addElement("--Chọn giới tính--");
        cbb.addElement("Nam");
        cbb.addElement("Nữ");
        
        cbb_gioitinh.setModel(cbb);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private com.toedter.calendar.JDateChooser calendar_ngaysinh;
    private javax.swing.JComboBox<String> cbb_gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_gv;
    private javax.swing.JTextField text_diachi;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_sdt;
    private javax.swing.JTextField text_tenGV;
    // End of variables declaration//GEN-END:variables
}
